config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
   }
  get '/users/:id', to: 'users#show', as: 'user'
  get 'calendar', to: 'events#calendar'
  resource :user, only: %i[edit] do
    collection do
      patch 'update_password'
    end
  end

  # カレンダー
  get 'statics', to: 'events#statics'
  get 'search', to: 'products#search'
  resources :events
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  def all_day_event?
    start == start.midnight && self.end == self.end.midnight ? true : false
  end

  def self.day_count_of_week(icon)
    week_range = (1.week.ago + 1.day).midnight..Time.zone.now.end_of_day
    where(icon: icon).group_by_day(:start, time_zone: 'Asia/Tokyo', range: week_range, format: '%d').count
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, uniqueness: true
  validates :username, presence: true, length: { maximum: 30 }
  validates :babyname, presence: true, length: { maximum: 30 }

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery except: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[babyname username memo sex])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[babyname username memo sex])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[edit update destroy]
  before_action :authenticate_user!

  def index
    @events = Event.where(start: params[:start]..params[:end])
    json = @events
    render json: json.to_json
  end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event.save
  end

  def update
    @event.update(event_params)
  end

  def destroy
    @event.destroy
  end

  def calendar; end

  def statics
    @milk = Event.day_count_of_week('milk.png')
    @breastfeeding = Event.day_count_of_week('breastfeeding.png')
    @poo = Event.day_count_of_week('poo.png')
    @pee = Event.day_count_of_week('pee.png')
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:start, :end, :color, :icon)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index; end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def search
    return unless params[:keyword]

    @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(_resource)
    calendar_path
  end

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(_resource)
    calendar_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user.update_with_password(user_params)
      bypass_sign_in(@user)
      flash[:notice] = 'パスワードが変更されました'
      redirect_to user_path(@user)
    else
      flash.now[:alert] = '変更に失敗しました'
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    return user.profile_photo unless user.profile_photo.nil?

    gravatar_id = Digest::MD5.hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_edit.html.erb
<div id="edit_event" class="modal modal-top fade calendar-modal">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-body">
				<div class="modal-header">
		      <h5 class="modal-title">イベント編集</h5>
		      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		        <span aria-hidden="true">&times;</span>
		      </button>
    		</div>
				<div class="modal-body" id="add-event">
          <%= render 'form', event: @event %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="form-group field">
  <%= form_with(model: @event, remote: true) do |f| %>
    <div class="form-inputs">
      <div class="form-group">
        <%= f.label :icon, "お世話内容", class: "form-control-label"%>
        <%= f.select :icon, [['ミルク', 'milk.png'], ['母乳', 'breastfeeding.png'], ['おしっこ', 'pee.png'], ['うんち', 'poo.png']], { selected: event.icon }, { class: "form-control input-icon" } %>
      </div>

      <div class="form-group">
        <%= f.label :color, "色", class: "form-control-label"%>
        <%= f.select :color, [['グレー', 'gray'], ['緑', 'teal'], ['オレンジ','orange']], { selected: '緑'  }, { class: "form-control" } %>
      </div>

      <div class="form-group">
        <%= f.label :start, "開始時間", class: "form-control-label"%>
        <div class="input-group date" id="datetimepicker7" data-target-input="nearest">
          <%= f.text_field :start, class: "form-control input-start", id: "datetimepicker7", data: { target: "#datetimepicker7", toggle: "datetimepicker" } %>
        </div>
      </div>

      <div class="form-group"> 
        <%= f.label :end, "終了時間", class: "form-control-label"%>
        <div class="input-group date" id="datetimepicker8" data-target-input="nearest">
          <%= f.text_field :end, class: "form-control input-end", id: "datetimepicker8", data: { target: "#datetimepicker8", toggle: "datetimepicker" } %>
        </div>
      </div>
    </div>
    <div class="modal-footer actions">
      <%= f.submit "入力完了", class: "btn btn-primary" %>
      <%= link_to '削除',
                  event,
                  method: :delete,
                  class: 'btn btn-danger',
                  data: { confirm: '削除してもよろしいですか?' },
                  remote: true unless @event.new_record? %>
    </div>
  <% end %>
</div>

app/views/events/_new.html.erb
<div id="new_event" class="modal modal-top fade calendar-modal">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-body">
				<div class="modal-header">
		      <h5 class="modal-title">イベント追加</h5>
		      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		        <span aria-hidden="true">&times;</span>
		      </button>
    		</div>
				<div class="modal-body" id="add-event">
          <%= render 'form', event: @event %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/calendar.html.erb
<div class="p-5">
  <h2 class="mb-4"><%= "#{current_user.babyname}ちゃんの記録" %></h2>
  <div class="card">
    <div class="card-body p-0">
      <div id="calendar"></div>
    </div>
  </div>
</div>

app/views/events/create.js.erb
$('#calendar').fullCalendar(
  'renderEvent',
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');

app/views/events/destroy.js.erb
$('#calendar').fullCalendar('removeEvents', [<%= @event.id %>])
$('.modal').modal('hide');

app/views/events/edit.js.erb
$('#remote_container').html('<%= j render "edit" %>');
$('#edit_event').modal('show');

app/views/events/new.js.erb
$('#remote_container').html('<%= j render "new" %>');
$('#new_event').modal('show');

app/views/events/show.html.erb
<div class="p-5">
  <h2 class="mb-4"><%= "#{current_user.babyname}ちゃんの記録" %></h2>
  <div class="card">
    <div class="card-body p-0">
      <div id="calendar"></div>
    </div>
  </div>
</div>

app/views/events/statics.html.erb
<div class="container p-5">
  <div type="button" class="switch-graph mb-2 btn btn-success" id="milk">ミルク</div>
  <div type="button" class="switch-graph mb-2 btn btn-warning" id="breastfeeding">母乳</div>
  <div type="button" class="switch-graph mb-2 btn btn-info" id="poo">うんち</div>
  <div type="button" class="switch-graph mb-2 btn btn-primary" id="pee">おしっこ</div>
  <%= column_chart @milk, title: "ミルクの回数", xtitle: "日付", ytitle: "回数", height: "400px", id: "milk-graph", colors: ["#28A744"] %>
  <%= column_chart @breastfeeding, title: "授乳回数", xtitle: "日付", ytitle: "回数", height: "400px", id: "breastfeeding-graph", colors: ["#f1da16"] %>
  <%= column_chart @poo, title: "うんちの回数", xtitle: "日付", ytitle: "回数", height: "400px", id: "poo-graph", colors: ["#13A3B8"] %>
  <%= column_chart @pee, title: "おしっこの回数", xtitle: "日付", ytitle: "回数", height: "400px", id: "pee-graph" %>
</div>

app/views/events/update.js.erb
$('#calendar').fullCalendar('removeEvents', [<%= @event.id %>]);
$('#calendar').fullCalendar(
  'renderEvent',
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');

app/views/homes/index.html.erb
<div class="main">
      <div class="form-group text-center">
        <h1 class="home-title">CHILED CALENDAR</h1>
        <img src="images/title.png" alt="" class="rounded-circle col-9">
      </div>
      <%= link_to "楽に育児管理をはじめよう！", new_user_session_path, class: "btn btn-warning home-btn" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyChildCallendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
    <link rel="stylesheet" href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome-font-awesome.min.css" >
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/locale/ja.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"></script>
  </head>
  <body>
    <%= render 'partial/navbar' if current_user %>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
    <div id='remote_container'></div>
  </body>
</html>

app/views/partial/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p>
        insta_clone
      </p>
    </div>
  </div>
</footer>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <ul class="navbar-nav  mr-auto">
      <li class="nav-item mr-4">
        <%= link_to "", calendar_path, class: "nav-link calendar", alt: "カレンダー" %>
      </li>
      <li class="nav-item mr-4">
        <%= link_to "", statics_path, class: "nav-link graph", alt: "グラフ" %>
      </li>
      <li class="nav-item mr-4">
          <%= link_to "", user_path(current_user), class: "nav-link profile-icon", id: "プロフィール" %>
      </li>
    </ul>
    <%= form_with(url: search_path, method: :get, local: true, class: "form-inline my-2 my-lg-0") do |f| %>
      <%= f.select :keyword, [['ミルク', '赤ちゃん　ミルク'], ['おむつ', '赤ちゃん　おむつ'], ['おもちゃ','赤ちゃん　おもちゃ'], ['服','赤ちゃん　服']], {}, { class: "form-control mr-sm-2" } %>
      <%= f.submit('検索',class: "btn btn-outline-success my-2 my-sm-0") %>
    <% end %>
  </div>
</nav>

app/views/products/search.html.erb
<h2 class="center">検索結果</h2>
<div class="container-fluid">
  <table id="productSizes" class="table table-bordered table-hover ">
    <thead>
      <tr>
        <th class ="narrow">番号</th>
        <th class ="wide">商品名</th>
        <th class ="narrow">画像</th>
        <th class ="narrow">値段</th>
      </tr>
    </thead>
    <tbody>

      <% i = 1 %>
      <% @items.each do |item| %>
        <tr>
        　<td class ="narrow"><%= i %></td><% i += 1 %>
        　<td class ="wide"><a href="<%= item['itemUrl'] %>" target="_blank"><%= item['itemName'] %></a></td>
          <td class ="narrow"><img class=" img-fluid" src="<%= item['mediumImageUrls'][0] %>"></td>
          <td class ="narrow"><%= item['itemPrice'] %>円</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_user.html.erb
<li>
  <%= image_tag avatar_url(@user), class: "round-img-for-list" %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Password Change") %>

<div class="main">
  <div class="devise-outer">
    <div class="form-wrap">
      <%= form_with model:@user, url: update_password_user_path, method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :current_password, "現在のパスワード" %>
          <%= f.password_field :current_password, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password, "新しいパスワード" %>
          <%= f.password_field :password, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "新しいパスワードの確認" %>
          <%= f.password_field :password_confirmation, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group text-center">
          <%= f.submit "変更する", class: "btn btn-primary" %>
        </div>
      <% end %>
      <br>
      <p><%= link_to "戻る", user_path(@user) %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="profile-wrap">
    <div class="row">
      <div class="col-md-4 text-center">
        <%= image_tag avatar_url(@user), class: "round-img" %>
      </div>
      <div class="col-md-8">
        <div class="row mb-2">
          <h1><%= @user.username %></h1>
          <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn-sticky edit-profile-btn" %>
          <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                  </button>
                </div>
                <div class="list-group text-center">
                  <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
                  <%= link_to "パスワードを変更", edit_user_path, method: :get,class: "list-group-item list-group-item-action" %>
                  <%= link_to "アカウントの削除", registration_path(:user), method: :delete,class: "list-group-item list-group-item-action btn-danger" %>
                  <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <p>赤ちゃんの名前：<%= @user.babyname %>
            <br>性別：<%= @user.sex %>
            <br>メモ：<%= @user.memo %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>